CREATE TABLE IF NOT EXISTS employee
(
  id VARCHAR(80) NOT NULL PRIMARY KEY,
  login VARCHAR(80) NOT NULL,
  name VARCHAR(80) NOT NULL,
  salary DECIMAL(80) DEFAULT NULL,
  startDate DATE DEFAULT NULL
);